import type { Task } from "./types";

const hoursFromNow = (h: number) => new Date(Date.now() + h * 3_600_000).toISOString();

export const sampleTasks: Task[] = [
  {
    id: "t1",
    title: "Calculus problem set §4.3",
    course: "Math 101",
    notes: "Skim notes first, then attempt 1-12.",
    deadline: hoursFromNow(20),
    effort_minutes: 75,
    difficulty: 3,
    status: "todo",
    progress_minutes: 0,
    emoji: "📐",
    created_at: new Date().toISOString(),
  },
  {
    id: "t2",
    title: "Lit review draft — Section 2",
    course: "English 210",
    notes: "Two paragraphs on the historiography debate.",
    deadline: hoursFromNow(50),
    effort_minutes: 180,
    difficulty: 4,
    status: "in_progress",
    progress_minutes: 45,
    emoji: "📚",
    created_at: new Date().toISOString(),
  },
  {
    id: "t3",
    title: "Group presentation slides",
    course: "BUS 240",
    notes: "Ana doing intro, you have slides 4–7.",
    deadline: hoursFromNow(96),
    effort_minutes: 120,
    difficulty: 2,
    status: "todo",
    progress_minutes: 0,
    emoji: "🎤",
    created_at: new Date().toISOString(),
  },
  {
    id: "t4",
    title: "Read CS textbook ch. 6",
    course: "CS 110",
    notes: "Quiz on Friday — annotate key terms.",
    deadline: hoursFromNow(60),
    effort_minutes: 90,
    difficulty: 2,
    status: "todo",
    progress_minutes: 0,
    emoji: "💻",
    created_at: new Date().toISOString(),
  },
  {
    id: "t5",
    title: "Final project — research milestone",
    course: "Bio 201",
    notes: "Pick the dataset and write the proposal.",
    deadline: hoursFromNow(168),
    effort_minutes: 360,
    difficulty: 5,
    status: "todo",
    progress_minutes: 30,
    emoji: "🧬",
    created_at: new Date().toISOString(),
  },
  {
    id: "t6",
    title: "Clean lab report typos",
    course: "Chem 105",
    notes: "Spotted 3 in the conclusion last night.",
    deadline: hoursFromNow(8),
    effort_minutes: 20,
    difficulty: 1,
    status: "todo",
    progress_minutes: 0,
    emoji: "🧪",
    created_at: new Date().toISOString(),
  },
];
